# Generated by Django 4.0.4 on 2022-05-11 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('gp_foco', models.CharField(choices=[('Peito', 'peito'), ('Biceps', 'biceps'), ('Triceps', 'triceps'), ('Costas', 'costas'), ('Posterior de Perna', 'pos_perna'), ('Perna', 'perna')], default='Peito', max_length=500)),
                ('gp_aux', models.CharField(blank=True, choices=[('Peito', 'peito'), ('Biceps', 'biceps'), ('Triceps', 'triceps'), ('Costas', 'costas'), ('Posterior de Perna', 'pos_perna'), ('Perna', 'perna')], default='Peito', max_length=500, null=True)),
            ],
        ),
    ]
