# Generated by Django 4.0.4 on 2022-05-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_set_alter_machine_gp_aux_alter_machine_gp_foco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Machine', to='app.machine', verbose_name='Machine'),
            preserve_default=False,
        ),
    ]
