# Generated by Django 4.0.4 on 2022-05-13 03:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_set_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sets', to='app.set', verbose_name='Sets')),
            ],
        ),
    ]
