# Generated by Django 4.0.4 on 2022-05-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_set_created_date_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.ManyToManyField(blank=True, related_name='Rep', to='app.rep'),
        ),
    ]
