# Generated by Django 4.0.4 on 2022-05-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rep_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='qtd',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
